calblueprint/peoplepower-web

src/lib/auth.js, src/lib/request.js
API key file was moved and master needed to correctly reference the file. 
CC: @aivantg
=> Edit import headers for api_key

src/lib/request.js
Updated `request.js` documentation on proper use of the functions.
Added and revised prior documentation on how to use `createRecord` and `updateRecord` functions. I also removed a `console.log` statement that was cluttering the console in development.
CC: @aivantg
=> Update request.js documentation 👍🏼

src/App.js, src/components/Bill.js, src/index.js, src/lib/auth.js, src/lib/request.js, src/lib/subscriberHelper.js, src/screens/general/Bill.js, src/screens/general/SubscriberOwnerDashboard.js, src/styles/Bill.css, src/styles/SubscriberOwnerDashboard.css
Create functionality to load a subscriber owner's bills from airtable, with the option to pay the latest bill
-
-
-
Current view (very functional)
CC: @aivantg
=> View bills for Subscriber Owners

src/lib/auth.js, src/screens/onboarding/ContactInfo.js, src/screens/onboarding/Onboarding.js
...once a finishes steps 1 and 2 (sign up phase)
CC: @aivantg
=> Add  function to create a user after the end of 'signup' phase

src/lib/auth.js
Implemented retries + rollback to rectify potential inconsistencies with creating records on signup
- https://github.com/calblueprint/peoplepower-web/pull/29
CC: @aivantg
=> Address potential inconsistency with Signup

src/components/NavBar.js, src/lib/paypal.js, src/lib/request.js
UNBREAK NOW @aivantg 
CC: @aivantg
=> Hot fix to unbreak master + update balance on payment for bill pay

src/App.js, src/components/NavBar.js, src/lib/credentials.js
Split "My Finances" to "Billing" for subscribers and "My Investment" for general owners. Also added a null check to the credentials.js' `applyCredentials` function.
CC: @aivantg
=> Nick/update-routes: RENAMING Navbar "My Finances" link.

src/components/LoadingComponent.js, src/screens/general/AdminDashboard.js, src/screens/general/Community.js, src/screens/general/GeneralOwnerDashboard.js, src/screens/general/SubscriberOwnerDashboard/SubscriberOwnerDashboard.js, src/screens/general/UserProfilePage.js, src/styles/App.css, src/styles/Community.css
Made a component called LoadingComponent that is a spinner to be rendered when waiting for async data arrival.
CC: @aivantg
=> implement loading component

src/components/AddAnnouncement.js, src/components/AnnouncementList.js, src/screens/general/Card.js, src/screens/general/GeneralOwnerDashboard.js, src/styles/AdminDashboard.css, src/styles/Community.css, src/styles/GeneralOwnerDashboard.css
Fixed css collisions between three different elements all with the same `card` class. Also updated text colors and font sizes to match the hi-fi designs.
CC: @aivantg
=> Nick/presentation STYLE UPDATES

src/constants.js, src/lib/adminHelper.js, src/lib/auth.js, src/lib/credentials.js, src/lib/onboardingUtils.js, src/lib/paypal.js, src/lib/request.js, src/lib/subscriberHelper.js
move Airtable table consts + other params into a constants.js file
CC: @aivantg
=> [Easy] Clean up constants

src/components/NavBar.js
Revert removal of Navbar field sin https://github.com/calblueprint/peoplepower-web/commit/d4ee63d8d7e87e7ae2d9e0440aa3265b880f5539
CC: @aivantg
=> [0] Revert deletion of nav bar fields in #41

.eslintrc.json, package.json, src/__tests__/lib/request.spec.js, yarn.lock
https://github.com/calblueprint/peoplepower-web/pull/44
CC: @aivantg
=> [1] setup basic jest testing infrastructure

src/App.js, src/components/NavBar.js, src/lib/credentials.js, src/screens/general/Community.js, src/screens/general/GeneralOwnerDashboard.js, src/screens/general/SubscriberOwnerDashboard/SubscriberOwnerDashboard.js, src/screens/general/SubscriberOwnerDashboard/SubscriberOwnerDashboardAllBillsView.js, src/screens/general/SubscriberOwnerDashboard/SubscriberOwnerDashboardMainView.js, src/screens/onboarding/BasicInfo.js, src/screens/onboarding/Complete.js, src/screens/onboarding/Onboarding.js
Describe your feature here
1. https://github.com/calblueprint/peoplepower-web/pull/43
2. https://github.com/calblueprint/peoplepower-web/pull/44
=> [3] Fix bug: correct navbar state management 

src/screens/auth/Login.js, src/screens/onboarding/Payment.js
[//]: # (Describe your feature here)
[//]: # (Optional - any related PRs you're waiting on, or PRs that will conflict, etc)
[//]: # (Optional - if you added anything to the database through migration[s])
[//]: # (If you made changes/additions to `airtable.js` or `request.js`,) 
[//]: # (make sure you update/add [at least 1] corresponding unit tests in)
[//]: # (`airtable.spec.js` or `request.spec.js`)
[//]: # (Add screenshots!!! If you'd like)
=> [Easy] Wrap login ard try catch + rename function

src/styles/AdminDashboard.css, src/styles/Community.css, src/styles/GeneralOwnerDashboard.css, src/styles/index.css
Remove font-family css from everywhere else
[//]: # (Describe your feature here)
[//]: # (Optional - any related PRs you're waiting on, or PRs that will conflict, etc)
[//]: # (Optional - if you added anything to the database through migration[s])
[//]: # (If you made changes/additions to `airtable.js` or `request.js`,) 
[//]: # (make sure you update/add [at least 1] corresponding unit tests in)
[//]: # (`airtable.spec.js` or `request.spec.js`)
[//]: # (Add screenshots!!! If you'd like)
=> [Easy] Add Avenir to all fonts in index.css

src/__tests__/lib/airtable.spec.js, src/lib/airtable.js
Actually test that `airtable.js` functions update airtable records appropriately
=> Make airtable.js tests more robust

src/lib/paypalUtils.js
=> [Urgent][Easy]Hotfix use of uppercase Balance causing NaN error

.github/pull_request_template.md, src/screens/general/SubscriberOwnerDashboard/SubscriberOwnerDashboardMainView.js
[//]: # (Describe your feature here)
[//]: # (Optional - any related PRs you're waiting on, or PRs that will conflict, etc)
[//]: # (Optional - if you added anything to the database through migration[s])
[//]: # (If you made changes/additions to `airtable.js` or `request.js`,) 
[//]: # (make sure you update/add [at least 1] corresponding unit tests in)
[//]: # (`airtable.spec.js` or `request.spec.js`)
[//]: # (Add screenshots!!! If you'd like)
=> [Easy] Minor changes to PR Template and style

README.md
Updated the README file to resolve ambiguity in how documentation is currently written
-
-
-
-
-
CC: @dfangshuo
=> [Easy] Add note to README

src/screens/onboarding/Onboarding.js, src/screens/onboarding/components/ProgressBar.js
There are small changes in regards to onboarding progress bar.
Renamed a parameter and changed some logical conditions
Go through onboarding and the progress bar indicator should be correct.
CC: @dfangshuo
=> fixed broken onboarding progress bar

src/App.js, src/components/NavBar.js, src/screens/general/GeneralDashboard.js, src/screens/shared/Community.js
Changed the NavBar to say "Project News" instead of "Community", button links to the same page as previous, and changed header on Project News page to say "Project News". 
Review NavBar.js, App.js
N/A
Leave note that Community.js has not been renamed to Project News.
N/A
CC: @dfangshuo
=> Project News Header

src/lib/subscriberUtils.js
Fixed a bug where the wrong key was used post airtable schema migration, causing the subscriber dashboard to break when trying to display bills
CC: @dfangshuo
=> [Easy] Fixed bug that broke payment on master

src/screens/shared/Community.js
Reversed ordering of posts so newer posts appear on top for UX reasons
https://github.com/calblueprint/peoplepower-web/pull/76/files
CC: @dfangshuo
=> [Easy] Community posts UX Improvements

src/screens/shared/Community.js
Reverse announcements - i'm a little confused why my previous PR didn't get its changed implemented even though it was merged, but here  it is again
CC: @dfangshuo
=> [Easy] Reverse announcements

src/lib/airtable/airtable.js
Fixed a bug where `getAllRecords` returns only the first page (instead of all records)
CC: @dfangshuo
=> [Easy] fix getAllRecords

src/screens/general/GeneralDashboard.js, src/styles/GeneralOwnerDashboard.css
[//]: # "#####################################"
[//]: # "####### YOUR ANSWER BELOW ###########"
- Addressed some implementation errors in #92, namely, the fact that the div for the investment box was nested within the solar projects div.
- Updated CSS to kebab case
- change the font of title to be grey like the rest of the titles
[//]: # "############## END ##################"
[//]: # "#####################################"
[//]: # "####### YOUR ANSWER BELOW ###########"
Spend most of your attention on how the div is structured. Notice how the solar projects and investment divs are nested in a larger div …
=> [2/2] updates to general owner dashboard PR #92

src/screens/onboarding/steps/BasicInfoStep.js, src/styles/Onboarding.css
- Created text and button at the bottom of create account page that allows users to go to login page if they already have an account
[//]: # "############## END ##################"
[//]: # "#####################################"
[//]: # "####### YOUR ANSWER BELOW ###########"
- BasicInfoStep.js and Onboarding.css
[//]: # "############## END ##################"
[//]: # "#####################################"
[//]: # "####### YOUR ANSWER BELOW ###########"
[//]: # "############## END ##################"
[//]: # "What doesn't work …
=> Already Have Account Button on Create Account Page

src/lib/airtable/schema.json, src/lib/airtable/schemaRaw.json, src/screens/admin/AdminDashboard.js
Change admin-modal pledge invite form to use store a boolean value on Airtable instead of the "multi-select" option.
[//]: # "############## END ##################"
[//]: # "#####################################"
[//]: # "####### YOUR ANSWER BELOW ###########"
[//]: # "############## END ##################"
[//]: # "#####################################"
[//]: # "####### YOUR ANSWER BELOW ###########"
[//]: # "############## END ##################"
[//]: # "#####################################"
[//]: # "####### YOUR ANSWER BELOW ###########"
[//]: # …
=> change wantDividends to boolean/checkbox

README.md, src/screens/shared/UserProfile.js, src/styles/UserProfilePage.css
User profile page now has two editing toggle buttons and input validation. styles to come!
[//]: # …
=> Update User Profile Page

src/screens/admin/AdminDashboard.js, src/styles/AdminDashboard.css
=> add in css from high-fi design to modal

src/components/LoadingComponent.js, src/components/PPLoadingSpinner.js, src/styles/LoadingComponent.css, src/styles/PPLoadingSpinner.css, src/styles/main.css
I Implemented the loading spinner Iris designed!
CC: @dfangshuo
=> Added Hi-Fi Loading Spinner

src/App.js, src/screens/subscriber/SubscriberWithSharesDashboard.js, src/screens/subscriber/components/BillingAllBillsView.js, src/screens/subscriber/components/BillingMainView.js, src/screens/subscriber/components/DashboardBillingSection.js, src/screens/subscriber/components/DashboardProjectNewsSection.js, src/styles/GeneralOwnerDashboard.css
- Cleaned up and made consistent button size on all dashboards
- Removed `SubscriberWithShares` dashboard since it's already in Subscriber dashboard …
=> [Easy] Quick Fixes 

src/screens/shared/UserProfile.js, src/styles/UserProfilePage.css
Added a cancel button to user profile page.
CC: @dfangshuo
=> Added Cancel Button to User Profile Page

src/screens/general/Investment.js, src/screens/general/components/DividendsPreferencesModal.js
Fixed small investment bug where default value for dividends was undefined
[//]: # "What doesn't work …
=> Fixed small investment bug using lifecycle methods

src/App.js, src/components/NavBar.js
- graying was not working properly on NavBar
- check NavBar.js
- why does pathname prop not update …
=> Fixing NavBar Graying Issue

src/screens/general/BuyShares.js, src/screens/general/Investment.js, src/styles/Investments.css
- changed caption of progress bar to "You currently own 3 shares,
you can buy up to 7 more shares."
- button to add/delete shares starts at 0 and can only go up to max_shares - owner.numberOfShares
- check BuyShares.js, Investments.css
[//]: # …
=> Buy Shares Page Updates 

package.json, src/lib/airtable/request.js, src/lib/airtable/schema.js, yarn.lock
Just bumping schema generator version with tiny fix + schema updates
[//]: # …
=> Schema Update

src/App.js, src/screens/general/GeneralDashboard.js, src/screens/subscriber/Billing.js, src/screens/subscriber/components/BillingAllTransactions.js
=> Clean up general owner panel for where charts should be + schema changes

src/screens/general/BuyShares.js
- changed caption for buy shares progress bar
[//]: # '#### YOUR SCREENSHOTS …
=> Caption Change

src/styles/SubscriberDashboard.css
Removes a scroll bar and handles overflow better on the subscriber dash. …
=> QUICKFIX subscriber dash scroll

public/manifest.json, src/screens/general/GeneralDashboard.js, src/screens/general/Investment.js, src/screens/shared/components/InvestmentWidget.js, src/styles/GeneralOwnerDashboard.css, src/styles/InvestmentWidget.css
- Renamed InvestmentCard -> InvestmentWidget for clarity
- Fixed UI bug where the chart and widget was not aligned
[//]: # …
=> Align solar project chart with my investments widget + some name changes

src/screens/general/Investment.js, src/screens/general/components/DividendsPreferencesModal.js, src/screens/onboarding/steps/BasicInfoStep.js, src/screens/onboarding/steps/CompleteStep.js, src/screens/subscriber/components/BillingPayment.js, src/styles/BillingPayment.css, src/styles/Investments.css, src/styles/Onboarding.css
- fixed modal size of very first landing onboarding step
- changed dividends preferences modal so that it would default choose what the user already has
- "back" the word is clickable on billing payment page
- when you hover over "Save Preferences" on dividends preferences modal it has the clicky cursor now
- checked the changed files! …
=> More Bug Fixes

public/index.html, public/manifest.json
=> [easy] fix background bugs

src/styles/Onboarding.css
- literally just centered onboarding tooltip arrow LOL
[//]: # '#### YOUR …
=> Centered Onboarding Tooltip Arrow

src/colors.js, src/lib/charts/createCostSavingsChart.js, src/lib/charts/createInvestmentBreakdownChart.js, src/lib/charts/createProductionChart.js, src/styles/AdminDashboard.css, src/styles/NavBar.css, src/styles/Onboarding.css, src/styles/PPModal.css, src/styles/main.css
=> [Easy][2] Move all colors into constants files

src/components/SettingsDropdown.js, src/lib/redux/userDataSlice.js, src/lib/userDataUtils.js, src/screens/admin/AdminDashboard.js, src/screens/auth/Login.js, src/screens/general/BuyShares.js, src/screens/onboarding/Onboarding.js, src/screens/subscriber/components/BillingPayment.js
A little hacky, but I was wondering if I could make some changes to redux to achieve similar functionality? @aivantg And if there's a better/easy way to do it, feel free to just push changes
[//]: # "What doesn't work yet, what's NOT in this …
=> Add global loading

src/screens/onboarding/steps/PaymentDetailsStep.js
=> [SO easy] fix bug where selecting yes at onboarding does nothing

src/lib/redux/userData.js
This change lets us make the primary key of project groups their name instead of their ID …
=> Update the way that announcements are gotten in airtable

src/App.js, src/components/AuthenticatedRoute.js, src/components/NavBar.js, src/lib/redux/userData.js, src/lib/redux/userDataSlice.js, src/screens/admin/AdminDashboard.js, src/screens/shared/Community.js
removed credentials from redux. simple update, makes app a tad bit more secure and clean
just confirm things work, especially credential-related things
[//]: # '####### YOUR …
=> removed credentials from redux

src/components/FeedbackButton.js, src/lib/adminUtils.js, src/lib/airlock/airlock.js, src/lib/billingUtils.js, src/lib/credentials.js, src/lib/highcharts/createCostSavingsChart.js, src/lib/highcharts/createInvestmentBreakdownChart.js, src/lib/highcharts/createProductionChart.js, src/lib/onboardingUtils.js, src/lib/paypal/paypal.js, src/lib/subscriberUtils.js, src/screens/admin/AdminDashboard.js, src/screens/onboarding/Onboarding.js, src/screens/onboarding/steps/PaymentDetailsStep.js, src/screens/subscriber/Billing.js
Some documentation and some cleanup! 
Just make sure i didn't break anything :P  …
=> added some documentation and cleanup

src/App.js
- On loading App.js, session clears if unauthorized and user is redirected to login …
=> [3] Session Clearing

src/screens/admin/AdminDashboard.js
=> fixed admin loading

src/components/SettingsDropdown.js, src/lib/airlock/airlock.js, src/lib/redux/userData.js
=> Better Loading Animation for Logout

src/lib/onboardingUtils.js, src/screens/onboarding/Onboarding.js
=> Fixed Alt. Email validation and skipped project group step if invited

src/styles/Login.css
=> Fixed small UI bug for safari (and uncovered an enormous Airlock bug LOL

src/lib/subscriberUtils.js, src/screens/subscriber/components/TransactionsTable.js
=> Added Links to Transaction Table

src/lib/billingUtils.js, src/lib/paypal/paypal.js, src/screens/general/BuyShares.js, src/screens/onboarding/steps/PaymentDetailsStep.js, src/screens/onboarding/steps/PaymentStep.js, src/screens/shared/components/PaymentSuccessCard.js, src/screens/subscriber/components/BillingPayment.js, src/styles/BuyShares.css
=> Add Transaction Fee to all pages + added notice to success screen

src/screens/shared/components/PaymentSuccessCard.js, src/styles/PaymentSuccessCard.css
=> [EASY]: Hide 'shares purchased' on payment success screen when paying a bill

src/App.js, src/components/SettingsDropdown.js, src/screens/auth/Login.js, src/screens/shared/About.js, src/screens/shared/Community.js, src/screens/shared/components/AddAnnouncement.js, src/screens/shared/components/InvestmentWidget.js, src/styles/App.css
Add modal for divest + forgot password 
Add announcement input for admins regardless of announcment count
[//]: # …
=> Modals for nonfunctional buttons + add announcement posting function to admins with empty state + about page
